# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='team_id',
            new_name='team',
        ),
    ]
